#! /bin/sh

cd /tmp/ \
&& tar xzf apache-tomcat.tar.gz \
&& mv apache-tomcat /opengrok/packs/ \
&& tar xzf opengrok.tar.gz \
&& mv opengrok /opengrok/packs/

source ~/.bashrc

/opengrok/packs/apache-tomcat/bin/startup.sh \
&& /opengrok/packs/opengrok/bin/OpenGrok deploy \
&& sleep 3 \
&& /opengrok/packs/opengrok/bin/OpenGrok index /projects

bash

