#! /bin/sh

cd /tmp/ \
&& tar xzf apache-tomcat.tar.gz -C /opengrok/packs \
&& tar xzf opengrok.tar.gz -C /opengrok/packs \
&& cd /opengrok/packs \
&& mv apache-tomcat* /opengrok/packs/apache-tomcat \
&& mv opengrok* /opengrok/packs/opengrok

source ~/.bashrc

/opengrok/packs/apache-tomcat/bin/startup.sh \
&& /opengrok/packs/opengrok/bin/OpenGrok deploy \
&& sleep 3 \
&& /opengrok/packs/opengrok/bin/OpenGrok index /projects

bash

