#! /bin/sh

cd /tmp/ \
&& tar xzf apache-tomcat.tar.gz -C /packs \
&& tar xzf opengrok.tar.gz -C /packs \
&& cd /packs \
&& mv apache-tomcat* /packs/apache-tomcat \
&& mv opengrok* /packs/opengrok

# 先启动环境
source ~/.bashrc.local

/packs/apache-tomcat/bin/startup.sh \
&& /packs/opengrok/bin/OpenGrok deploy \
&& sleep 3 \
&& /packs/opengrok/bin/OpenGrok index /projects

# bash 配置
echo "" >> ~/.bashrc
echo "if [ -f ~/.bashrc.local ];then "  >> ~/.bashrc
echo "    source ~/.bashrc.local;"   >> ~/.bashrc
echo "fi" >> ~/.bashrc
echo "" >> ~/.bashrc
/bin/bash

